name: Docker Image CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build and tag Docker image
      run: |
        docker build . --file Dockerfile --tag vidyudabhi/self-blog:latest
        docker tag vidyudabhi/self-blog:latest vidyudabhi/self-blog:$(date +%s)

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push vidyudabhi/self-blog:latest
        docker push vidyudabhi/self-blog:$(date +%s)

    - name: Clean up unused Docker images
      run: docker image prune --force
